dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    rooms:
      secure: eNAtd+8ftjoEThKI0iT1wDF50mAdrhob3snyOIBerNph3fNAjOsD+UUgjSXrzORi5TY8iujm1UH0LWQZsWQ58nBQBZQN+3VOhDhvl5HzPBpMsgUsUzEdLtnkblN6AansFPabIOJhoiM/fAGCyevOjLBL1nIkuXi+PzKi1Ns1wtXxDEj1cfd5KnvpBii9TmQEjsTUuOANfeXrspiXLUdudGnm40VkpfFjsaYV/3MUrHmhxq/PKYa4XKOMBR0w1uioNjA6y4R/qch4yjT1fm3a3Wp6gnDruPahmTlq89cCV9OrS7wqSSRbZUB9XwNlMMiFCKRu14Y+2PZEOI63p4LsY0TxAuYLKX1ufZG4H0mAlVMUUO4zJFhblx6cRbC59pokpsYvNkPrIAeWXwRxVPra81PwfagBezdU7qgPWdPqUJ6l3aZ2oqbUCmNFK8kVjYW18RLE0ze29w3xUsFziL3eTmkpZRROxux0IAd7X7TlRCwZ97Q7zV2ocSsHHTR3e4SvLwpIGw172mlskYj4KG1tJG4ETXlQpiSMoKCHZAY+ljzd4SSV0KEWu6IAzthvYrDwjP1mUATSTMpUdsdO6kvjtUQbxXS4trfqMvadlRwengmRj59suota5DnOGCVILF79moPBAsfFdTC02ix8Io+Z/UN1zmBRHyZLuEmBebEorjI=
