comment:
  image:
    repository: kumite/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: kumite/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: kumite/ui
    tag: latest
    service:
      externalPort: 9292
