- hosts: all
  tasks:
  - name: Add Docker GPG key
    become: true
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    become: true
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install list of packages
    become: true
    apt:
      name: "{{ item }}"
      state: installed
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - docker-compose

  - name: Create directory
    become: true
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /srv/gitlab/config
      - /srv/gitlab/data
      - /srv/gitlab/logs

  - name: Create docker-compose.yml
    become: true
    copy:
      src: ~/kumite73_microservices/gitlab-ci/docker-compose.yml
      dest: /srv/gitlab/docker-compose.yml

  - name: Install docker-machine
    become: true
    shell: |
      base=https://github.com/docker/machine/releases/download/v0.14.0 && \
      curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine \
      && sudo install /tmp/docker-machine /usr/local/bin/docker-machine
    args:
      executable: /bin/bash

  - name: Create create-runners.sh
    become: true
    copy:
      src: ~/kumite73_microservices/gitlab-ci/create-runners.sh
      dest: /srv/gitlab/create-runners.sh
      mode: 775
